apiVersion: v1
kind: Config
preferences: {}
current-context: default
clusters:
- cluster:
    server: https://MASTER_IP:6443
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: admin
  name: default
users:
- name: admin
  user:
    password: admin
    username: admin
