apiVersion: v1
kind: Config
preferences: {}
current-context: default
clusters:
- cluster:
    server: http://MASTER_IP:8080
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: ""
  name: default
users: {}
